version: '3.4'
services:
  node:
    image: cl-itau-bff-tesoreria-costfund:development
    build:
      context: .
      dockerfile: ./Dockerfile
      target: development
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - .env
    volumes:
      - "./:/usr/src/app"
      - "/usr/src/app/node_modules"
      - ./.aws/:/home/app/.aws/
    command: npm run start:dev
