apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: secrets-provider-financial-instrument-valuation-models
  namespace: models
spec:
  provider: aws
  secretObjects:
    - secretName: secrets-qa-bcl-dynamodb-financial-instrument-valuation-models
      type: Opaque
      data:
        - objectName: aws-dynamodb-accesskeyid
          key: aws-clientid
        - objectName: aws-dynamodb-secretaccesskey
          key: aws-clientapikey
        - objectName: aws-dynamodb-region
          key: aws-region
    - secretName: secrets-qa-inner-bcl-financial-instrument-valuation-models
      type: Opaque
      data:
        - objectName: inner-bcl-clienteid
          key: bcl-clientid
        - objectName: inner-bcl-apikey
          key: bcl-apikey       
  parameters:
    objects: |
      - objectName: "APIKey/qa/inner/bcl/tesoreria"
        objectType: secretsmanager
        jmesPath:
          - path: clientid
            objectAlias: inner-bcl-clienteid
          - path: clientsecret
            objectAlias: inner-bcl-apikey
      - objectName: "Password/qa/Dynamodb/Tesopro"
        objectType: secretsmanager
        jmesPath:
          - path: region  
            objectAlias: aws-dynamodb-region
          - path: accesskeyid
            objectAlias: aws-dynamodb-accesskeyid
          - path: secretaccesskey
            objectAlias: aws-dynamodb-secretaccesskey